In [1]:
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By

In [2]:
rank_list=[]
category=[]
company=[]
country=[]
market_capital=[]

##  Market Cap

In [3]:

# Set up the Chrome WebDriver (you need to have ChromeDriver installed and in your PATH)




def loop():
    global c_i
    global company
    global country
    
    
    company.append(driver.find_element(By.XPATH,'//*[@id="cmkt"]/div[5]/table/tbody/tr[' + str(c_i) + ']/td[3]/div[2]/a/div[1]').text)

    market_capital.append(driver.find_element(By.XPATH,'//*[@id="cmkt"]/div[5]/table/tbody/tr[' + str(c_i) + ']/td[4]').text)

    country.append(driver.find_element(By.XPATH,'//*[@id="cmkt"]/div[5]/table/tbody/tr[' + str(c_i) + ']/td[8]/span').text)
       
        



# page iteration
for pg_id in range(1,2): 
    driver = webdriver.Chrome()

    url = f"https://companiesmarketcap.com/automakers/largest-automakers-by-market-cap/"
    driver.get(url)        

    c_i = 1

    for i in range(1,61):

        r_iter=i
        
        cat='🚗 Automakers'
        category.append(cat)
        
        if pg_id == 1:
            rank=i
            
        elif pg_id == 2:
            rank=i+100
           
        elif pg_id == 3:
            rank=i+200
            
        elif pg_id == 4:
            rank=i+300   
            
        elif pg_id == 5:
            rank=i+400 
        
        elif pg_id == 6:
            rank=i+500 
         
        else:
            rank=i+600 
            
        rank_list.append(rank)
            

        if r_iter==18 or r_iter == 76:
            c_i +=1
            loop()

        else:
            loop()

        c_i+=1

    driver.close()

In [4]:
data = {'Rank':rank_list,'Category': category, 'Company': company, 'Market_Capital': market_capital,'Country':country}
df_MP=pd.DataFrame(data)
df_MP

,Rank,Category,Company,Market_Capital,Country
0,1,🚗 Automakers,Tesla,$755.72 B,USA
1,2,🚗 Automakers,Toyota,$253.75 B,Japan
2,3,🚗 Automakers,BYD,$87.30 B,China
3,4,🚗 Automakers,Porsche,$85.95 B,Germany
4,5,🚗 Automakers,Mercedes-Benz,$68.53 B,Germany
5,6,🚗 Automakers,BMW,$67.62 B,Germany
6,7,🚗 Automakers,Ferrari,$66.68 B,Italy
7,8,🚗 Automakers,Stellantis,$63.06 B,Netherlands
8,9,🚗 Automakers,Volkswagen,$62.24 B,Germany
9,10,🚗 Automakers,Honda,$51.40 B,Japan
10,11,🚗 Automakers,Li Auto,$42.73 B,China
11,12,🚗 Automakers,Ford,$41.95 B,USA
12,13,🚗 Automakers,General Motors,$38.70 B,USA
13,14,🚗 Automakers,Maruti Suzuki India,$38.12 B,India
14,15,🚗 Automakers,Hyundai,$34.20 B,S. Korea
15,16,🚗 Automakers,Tata Motors,$29.65 B,India
16,17,🚗 Automakers,Great Wall Motors,$27.08 B,China
17,18,🚗 Automakers,Kia,$25.51 B,S. Korea
18,19,🚗 Automakers,SAIC Motor,$23.83 B,China
19,20,🚗 Automakers,Mahindra & Mahindra,$23.18 B,India
20,21,🚗 Automakers,Chongqing Changan,$21.40 B,China
21,22,🚗 Automakers,Suzuki Motor,$19.47 B,Japan
22,23,🚗 Automakers,XPeng,$17.89 B,China
23,24,🚗 Automakers,Seres Group,$16.02 B,China
24,25,🚗 Automakers,Nissan,$15.62 B,Japan
25,26,🚗 Automakers,Rivian,$15.58 B,USA
26,27,🚗 Automakers,VinFast Auto,$14.84 B,Vietnam
27,28,🚗 Automakers,NIO,$13.89 B,China
28,29,🚗 Automakers,Subaru,$13.60 B,Japan
29,30,🚗 Automakers,Hotai Motor,$12.22 B,Taiwan
30,31,🚗 Automakers,Volvo Car,$12.06 B,Sweden
31,32,🚗 Automakers,Geely,$11.84 B,China
32,33,🚗 Automakers,GAC (Guangzhou Automobile Group),$11.59 B,China
33,34,🚗 Automakers,Renault,$11.04 B,France
34,35,🚗 Automakers,Isuzu,$9.97 B,Japan
35,36,🚗 Automakers,Ford Otosan,$9.96 B,Turkey
36,37,🚗 Automakers,Lucid Motors,$9.82 B,USA
37,38,🚗 Automakers,Mazda,$7.04 B,Japan
38,39,🚗 Automakers,FAW Car,$6.02 B,China
39,40,🚗 Automakers,Leapmotor,$5.84 B,China
40,41,🚗 Automakers,Polaris,$5.12 B,USA
41,42,🚗 Automakers,Mitsubishi Motors,$4.94 B,Japan
42,43,🚗 Automakers,Polestar,$4.45 B,Sweden
43,44,🚗 Automakers,Tofaş Türk Otomobil Fabrikası,$4.15 B,Turkey
44,45,🚗 Automakers,Dongfeng Motor,$3.93 B,China
45,46,🚗 Automakers,Aston Martin,$2.44 B,UK
46,47,🚗 Automakers,NWTN Inc.,$2.07 B,UAE
47,48,🚗 Automakers,Nikola,$1.01 B,USA
48,49,🚗 Automakers,Fisker,$0.76 B,USA
49,50,🚗 Automakers,Force Motors,$0.63 B,India
50,51,🚗 Automakers,Kandi Technologies Group,$0.24 B,China
51,52,🚗 Automakers,Canoo,$0.23 B,USA
52,53,🚗 Automakers,Mullen Automotive,$71.83 M,USA
53,54,🚗 Automakers,Cenntro Electric Group,$69.74 M,USA
54,55,🚗 Automakers,Electra Meccanica,$49.38 M,Canada
55,56,🚗 Automakers,REE Automotive,$36.91 M,Israel
56,57,🚗 Automakers,Phoenix Motor,$26.82 M,USA
57,58,🚗 Automakers,Arrival,$22.41 M,UK
58,59,🚗 Automakers,Faraday Future,$9.26 M,USA
59,60,🚗 Automakers,Arcimoto,$6.16 M,USA

In [5]:
df_MP = df_MP [df_MP.Market_Capital != 'N/A']

In [6]:
df_MP['Market_Capital']=df_MP['Market_Capital'].str.replace('$','')

/var/folders/fx/sxss674s30jf3yw9m3qmqvrm0000gn/T/ipykernel_2897/2648830908.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_MP['Market_Capital']=df_MP['Market_Capital'].str.replace('$','')

In [7]:
df_MP.to_csv('Automobile_MarketCapital.csv',index=False)

## Revenue

In [48]:

# Set up the Chrome WebDriver (you need to have ChromeDriver installed and in your PATH)

rank_list=[]
company=[]
revenue=[]


def loop():
    global c_i
    global company
    
    
    company.append(driver.find_element(By.XPATH,'//*[@id="cmkt"]/div[5]/table/tbody/tr[' + str(c_i) + ']/td[3]/div[2]/a/div[1]').text)

    revenue.append(driver.find_element(By.XPATH,'//*[@id="cmkt"]/div[5]/table/tbody/tr[' + str(c_i) + ']/td[4]').text)

       
        



# page iteration
for pg_id in range(1,2): 
    driver = webdriver.Chrome()

    url = f"https://companiesmarketcap.com/automakers/largest-automakers-by-revenue/"

    driver.get(url)        

    c_i = 1

    for i in range(1,61):

        r_iter=i
        
        cat=' 🍴 Food'
        category.append(cat)
        
        if pg_id == 1:
            rank=i
            
        elif pg_id == 2:
            rank=i+100
           
        elif pg_id == 3:
            rank=i+200
        
        elif pg_id == 4:
            rank=i+300   
            
        elif pg_id == 5:
            rank=i+400 
        
        elif pg_id == 6:
            rank=i+500 
         
        else:
            rank=i+600 
            
        rank_list.append(rank)
            

        if r_iter==18 or r_iter == 76:
            c_i +=1
            loop()

        else:
            loop()

        c_i+=1

    driver.close()     
            


data = {'Rank':rank_list,'Company': company, 'Revenue': revenue}
df_rev=pd.DataFrame(data)
df_rev


df_rev=df_rev[df_rev.Revenue != 'N/A']
df_rev.reset_index(drop=True, inplace=True)


df_rev['Revenue']=df_rev['Revenue'].str.replace('$','')



df_rev.to_csv('Automobile_Revenue.csv',index=False)

/var/folders/fx/sxss674s30jf3yw9m3qmqvrm0000gn/T/ipykernel_2897/584494180.py:85: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_rev['Revenue']=df_rev['Revenue'].str.replace('$','')

## Pharma - Employees

In [50]:

# Set up the Chrome WebDriver (you need to have ChromeDriver installed and in your PATH)

rank_list=[]

company=[]

employees=[]   


def loop():
    global c_i
    global company
    global country
    
    
    company.append(driver.find_element(By.XPATH,'//*[@id="cmkt"]/div[5]/table/tbody/tr[' + str(c_i) + ']/td[3]/div[2]/a/div[1]').text)

    employees.append(driver.find_element(By.XPATH,'//*[@id="cmkt"]/div[5]/table/tbody/tr[' + str(c_i) + ']/td[4]').text)

       
        



# page iteration
for pg_id in range(1,2): 
    driver = webdriver.Chrome()

    url = f"https://companiesmarketcap.com/automakers/largest-automakers-by-number-of-employees/"


    driver.get(url)        

    c_i = 1

    for i in range(1,61):

        r_iter=i
   
        if pg_id == 1:
            rank=i
            
        elif pg_id == 2:
            rank=i+100
           
        elif pg_id == 3:
            rank=i+200
            
        elif pg_id == 4:
            rank=i+300   
            
        elif pg_id == 5:
            rank=i+400 
        
        elif pg_id == 6:
            rank=i+500 
         
        else:
            rank=i+600 
            
        rank_list.append(rank)
            

        if r_iter==18 or r_iter == 76:
            c_i +=1
            loop()

        else:
            loop()

        c_i+=1

    driver.close()     
            


data = {'Rank':rank_list, 'Company': company, 'Employees': employees}
df_emp=pd.DataFrame(data)
df_emp

df_emp=df_emp[df_emp.Employees !='N/A']
df_emp.to_csv('Automobile_Emp.csv',index=False)

In [34]:
df_emp.to_csv('Automobile_Emp.csv',index=False)

## Pharma - Earnings

In [49]:
rank_list=[]
company=[]
earnings=[] 

# Set up the Chrome WebDriver (you need to have ChromeDriver installed and in your PATH)
def loop():
    global c_i
    global company
 
    
    
    company.append(driver.find_element(By.XPATH,'//*[@id="cmkt"]/div[5]/table/tbody/tr[' + str(c_i) + ']/td[3]/div[2]/a/div[1]').text)

    earnings.append(driver.find_element(By.XPATH,'//*[@id="cmkt"]/div[5]/table/tbody/tr[' + str(c_i) + ']/td[4]').text)

        



# page iteration
for pg_id in range(1,2): 
    driver = webdriver.Chrome()

    url = f"https://companiesmarketcap.com/automakers/most-profitable-automakers/"


    driver.get(url)        

    c_i = 1

    for i in range(1,61):

        r_iter=i
       
        
        if pg_id == 1:
            rank=i
            
        elif pg_id == 2:
            rank=i+100
           
        elif pg_id == 3:
            rank=i+200
            
        elif pg_id == 4:
            rank=i+300   
            
        elif pg_id == 5:
            rank=i+400 
        
        elif pg_id == 6:
            rank=i+500 
         
        else:
            rank=i+600 
            
        rank_list.append(rank)
            

        if r_iter==18 or r_iter == 76:
            c_i +=1
            loop()

        else:
            loop()

        c_i+=1

    driver.close()     
            

data = {'Rank':rank_list, 'Company': company, 'Earnings': earnings}

df_earn=pd.DataFrame(data)
df_earn


df_earn=df_earn[df_earn.Earnings !='N/A']
df_earn.to_csv('Automobile_Earning.csv',index=False)

## Pharma - P/E Ratio

In [43]:
rank_list=[]

company=[]

p_e=[]

In [44]:
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By


# Set up the Chrome WebDriver (you need to have ChromeDriver installed and in your PATH)
def loop():
    global c_i
    global company
    global p_e
    
    
    company.append(driver.find_element(By.XPATH,'//*[@id="cmkt"]/div[6]/table/tbody/tr[' + str(c_i) + ']/td[3]/div[2]/a/div[1]').text)

    p_e.append(driver.find_element(By.XPATH,'//*[@id="cmkt"]/div[6]/table/tbody/tr[' + str(c_i) + ']/td[4]').text)




# page iteration
for pg_id in range(1,2): 
    driver = webdriver.Chrome()

    url = f"https://companiesmarketcap.com/automakers/automakers-ranked-by-pe-ratio/"


    driver.get(url)        

    c_i = 1

    for i in range(1,61):

        r_iter=i
    
        
        if pg_id == 1:
            rank=i
            
        elif pg_id == 2:
            rank=i+100
           
        elif pg_id == 3:
            rank=i+200
            
        elif pg_id == 4:
            rank=i+300   
            
        elif pg_id == 5:
            rank=i+400 
        
        elif pg_id == 6:
            rank=i+500 
         
        else:
            rank=i+600 
            
        rank_list.append(rank)
            

        if r_iter==18 or r_iter == 76:
            c_i +=1
            loop()

        else:
            loop()

        c_i+=1

    driver.close()

In [45]:
data = {'Rank':rank_list,'Company': company, 'PE_Ratio': p_e}

df_pe=pd.DataFrame(data)
df_pe

    Rank                           Company PE_Ratio
0      1                    Dongfeng Motor     2.78
1      2                           Hyundai     2.95
2      3                 Mitsubishi Motors     3.79
3      4                        Volkswagen     3.88
4      5                    General Motors     3.93
5      6                     Mercedes-Benz     4.16
6      7                               Kia     4.54
7      8                               BMW     5.58
8      9                             Mazda     5.81
9     10                              Ford     6.66
10    11                       Ford Otosan     6.82
11    12     Tofaş Türk Otomobil Fabrikası     6.89
12    13                            Nissan     7.52
13    14                            Subaru     7.69
14    15                             Isuzu     8.39
15    16                             Honda     8.44
16    17                         Volvo Car     8.49
17    18                           Polaris     8.67
18    19                            Toyota     9.15
19    20                      Suzuki Motor     11.6
20    21                        SAIC Motor     12.3
21    22               Mahindra & Mahindra     14.6
22    23  GAC (Guangzhou Automobile Group)     15.0
23    24                 Chongqing Changan     16.0
24    25                             Geely     16.5
25    26                      Force Motors     19.9
26    27               Maruti Suzuki India     28.7
27    28                               BYD     32.4
28    29                 Great Wall Motors     35.9
29    30                           Ferrari     52.1
30    31                             Tesla     68.7
31    32                           Li Auto      156
32    33                       Tata Motors      341
33    34                           Renault    -28.3
34    35                            Nikola  -0.5949
35    36                               NIO    -4.14
36    37                      Aston Martin     -463
37    38                       Hotai Motor    -35.9
38    39                             XPeng    -12.2
39    40                 Electra Meccanica  -0.4353
40    41                          Arcimoto  -0.0403
41    42                            Fisker    -1.28
42    43                           FAW Car  < -1000
43    44                        Stellantis     10.6
44    45                             Canoo  -0.3161
45    46                           Arrival  -0.0104
46    47                      Lucid Motors    -2.94
47    48                            Rivian    -2.47
48    49                    REE Automotive  -0.4988
49    50            Cenntro Electric Group    -1.35
50    51                 Mullen Automotive  -0.0013
51    52                    Faraday Future  -0.0063
52    53                     Phoenix Motor    -1.71
53    54                          Polestar    -15.3
54    55          Kandi Technologies Group    -55.5
55    56                           Porsche      N/A
56    57                         Leapmotor    -12.2
57    58                      VinFast Auto    -5.98
58    59                         NWTN Inc.     -172
59    60                       Seres Group    -30.6

In [46]:
df_pe=df_pe[df_pe.PE_Ratio !='N/A']

In [47]:
df_pe.to_csv('Automobile_PE_ratio.csv',index=False)